const state={models:[],settings:null,currentJob:null,currentPage:1,previewMode:"compare",pollTimer:null,modelTask:null};
const $=(selector)=>document.querySelector(selector);const $$=(selector)=>[...document.querySelectorAll(selector)];
async function api(path,options={}){const response=await fetch(path,{headers:{"Content-Type":"application/json",...(options.headers||{})},...options});if(!response.ok){let message=`HTTP ${response.status}`;try{const body=await response.json();message=body.detail||message}catch{}throw new Error(message)}return response.json()}
function toast(message,error=false){const el=$("#toast");el.textContent=message;el.className=`toast show${error?" error":""}`;clearTimeout(el._timer);el._timer=setTimeout(()=>el.className="toast",3600)}
function escapeHtml(value){return String(value).replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[char])}
function modelIcon(id){return id==="paddleocr"?"PD":id==="manga-ocr"?"漫":"译"}
function renderModels(){const rows=state.models.map(model=>`<div class="model-row"><span class="model-icon">${modelIcon(model.id)}</span><div><b>${escapeHtml(model.name)}</b><small>${escapeHtml(model.role)} · ${escapeHtml(model.provider)}</small></div><span class="status-chip ${model.ready?"ready":""}">${model.ready?"已就绪":"未下载"}</span></div>`).join("");$("#modelRows").innerHTML=rows||'<div class="empty-list">模型状态不可用</div>';$("#modelListLarge").innerHTML=state.models.map(model=>`<article class="panel utility-item"><div><b>${escapeHtml(model.name)}</b><small>${escapeHtml(model.repository)} · ${escapeHtml(model.size)} · ${escapeHtml(model.license)}</small><small>${escapeHtml(model.path)}</small></div><span class="status-chip ${model.ready?"ready":""}">${model.ready?"已就绪":"未下载"}</span></article>`).join("");const missing=state.models.filter(model=>model.required&&!model.ready);$("#bootstrapModels").hidden=missing.length===0;$("#bootstrapModelsLarge").textContent=missing.length?`准备 ${missing.length} 个缺失模型`:"全部模型已就绪";$("#bootstrapModelsLarge").disabled=missing.length===0;updateStartState()}
async function refreshModels(){try{const data=await api("/api/models?refresh=true");state.models=data.models;renderModels()}catch(error){toast(error.message,true)}}
async function bootstrapModels(){const missing=state.models.filter(model=>!model.ready).map(model=>model.id);if(!missing.length)return;try{const task=await api("/api/models/bootstrap",{method:"POST",body:JSON.stringify({model_ids:missing})});state.modelTask=task.id;$("#modelProgress").hidden=false;pollModelTask()}catch(error){toast(error.message,true)}}
async function pollModelTask(){if(!state.modelTask)return;try{const task=await api(`/api/tasks/${state.modelTask}`);const progress=$("#modelProgress");progress.hidden=false;progress.querySelector("i").style.width=`${task.progress}%`;progress.querySelector("small").textContent=task.message;if(task.status==="complete"){state.modelTask=null;progress.hidden=true;toast("模型已准备完成");await refreshModels()}else if(task.status==="failed"){state.modelTask=null;progress.querySelector("small").textContent=task.error||task.message;toast(task.error||task.message,true)}else setTimeout(pollModelTask,1000)}catch(error){toast(error.message,true)}}
function loadSettings(settings){state.settings=settings;$("#targetLanguage").value=settings.target_language;$("#storyContext").checked=settings.story_context;$("#contextPages").value=settings.context_pages;$("#preserveSfx").checked=settings.preserve_sfx;$("#deviceSetting").value=settings.device;$("#preferModelscope").checked=settings.prefer_modelscope}
function collectSettings(){return{target_language:$("#targetLanguage").value,story_context:$("#storyContext").checked,context_pages:Number($("#contextPages").value),preserve_sfx:$("#preserveSfx").checked,prefer_modelscope:$("#preferModelscope").checked,device:$("#deviceSetting").value}}
async function saveSettings(){const settings=collectSettings();try{loadSettings(await api("/api/settings",{method:"PUT",body:JSON.stringify(settings)}))}catch(error){toast(error.message,true)}}
async function pickFolder(target){try{const initial=$(target).value||null;const result=await api("/api/dialog/folder",{method:"POST",body:JSON.stringify({initial})});if(result.path){$(target).value=result.path;if(target==="#sourcePath"&&!$("#outputPath").value)await deriveOutput();updateStartState()}}catch(error){toast(`${error.message}；也可以直接输入绝对路径。`,true)}}
async function deriveOutput(){const source=$("#sourcePath").value.trim();if(!source)return;try{const result=await api("/api/paths/derive-output",{method:"POST",body:JSON.stringify({initial:source})});$("#outputPath").value=result.path;updateStartState()}catch(error){toast(error.message,true)}}
function updateStartState(){const missing=state.models.some(model=>model.required&&!model.ready);const running=state.currentJob&&["queued","running"].includes(state.currentJob.status);$("#startButton").disabled=!$("#sourcePath").value.trim()||!$("#outputPath").value.trim()||missing||running;$("#startButton").title=missing?"请先准备缺失模型":""}
async function startJob(){const payload={source:$("#sourcePath").value.trim(),output:$("#outputPath").value.trim(),...collectSettings(),glossary:{}};try{state.currentJob=await api("/api/jobs",{method:"POST",body:JSON.stringify(payload)});state.currentPage=1;renderJob(state.currentJob);pollJob()}catch(error){toast(error.message,true)}}
function phaseIndex(job){if(job?.phase==="ocr")return job.total&&job.current/job.total>=.5?1:0;if(job?.phase==="translate")return 2;if(job?.phase==="render"||job?.phase==="complete")return 3;return 0}
function renderPipeline(job){const active=phaseIndex(job);$$('.pipeline-step').forEach((step,index)=>{step.classList.toggle("done",job?.status==="complete"||index<active);step.classList.toggle("active",job?.status==="running"&&index===active)});$$('.step-line').forEach((line,index)=>line.classList.toggle("done",job?.status==="complete"||index<active));$("#pipelineEstimate").textContent=job?.status==="running"?`${job.progress}%`:job?.status==="complete"?"已完成":"等待开始"}
function renderJob(job){state.currentJob=job;renderPipeline(job);$("#jobMessage").textContent=job.message||"等待开始";$("#jobDetail").textContent=job.error||`${job.phase||"queued"} · 本地任务`;$("#jobProgress").style.width=`${job.progress||0}%`;$("#jobCount").textContent=`${job.current||0} / ${job.total||0}`;$("#pageTotal").textContent=job.total||0;$("#pageNumber").textContent=job.total?state.currentPage:0;$("#activityRing").style.animation=job.status==="running"?"spin 1s linear infinite":"none";updateStartState();if(job.total)renderPreview();if(job.status==="failed")toast(job.error||"任务失败",true)}
async function pollJob(){clearTimeout(state.pollTimer);if(!state.currentJob)return;try{const job=await api(`/api/jobs/${state.currentJob.id}`);renderJob(job);if(["queued","running"].includes(job.status))state.pollTimer=setTimeout(pollJob,1000);else if(job.status==="complete"){toast("本地化完成");await refreshJobs()}}catch(error){toast(error.message,true)}}
function renderPreview(){const job=state.currentJob;if(!job||!job.total)return;const canvas=$("#previewCanvas");canvas.className=`preview-canvas mode-${state.previewMode}`;canvas.classList.remove("empty");$("#sourcePreview").src=`/api/jobs/${job.id}/preview/source/${state.currentPage}?t=${Date.now()}`;$("#outputPreview").src=`/api/jobs/${job.id}/preview/output/${state.currentPage}?t=${Date.now()}`;$("#outputPreview").onerror=()=>$("#outputPreview").removeAttribute("src");$("#previewName").textContent=`第 ${state.currentPage} 页`;$("#pageNumber").textContent=state.currentPage;$("#prevPage").disabled=state.currentPage<=1;$("#nextPage").disabled=state.currentPage>=job.total}
async function refreshJobs(){try{const data=await api("/api/jobs");const list=$("#jobList");list.innerHTML=data.jobs.length?data.jobs.map(job=>`<button class="panel utility-item job-item" data-job-id="${job.id}"><div><b>${escapeHtml(job.request.source)}</b><small>${escapeHtml(job.message)} · ${job.progress}% · ${escapeHtml(job.updated_at)}</small></div><span class="status-chip ${job.status==="complete"?"ready":job.status==="failed"?"error":""}">${escapeHtml(job.status)}</span></button>`).join(""):'<div class="panel empty-list">还没有任务记录</div>';$$('.job-item').forEach(button=>button.addEventListener("click",async()=>{const job=await api(`/api/jobs/${button.dataset.jobId}`);renderJob(job);switchView("workspace")}))}catch(error){toast(error.message,true)}}
function switchView(view){$$('.nav-item').forEach(button=>button.classList.toggle("active",button.dataset.view===view));$$('.view').forEach(panel=>panel.classList.toggle("active",panel.dataset.viewPanel===view));const labels={workspace:"漫画本地化工作台",history:"任务记录",models:"模型管理",settings:"设置"};$("#pageTitle").textContent=labels[view]||labels.workspace;if(view==="history")refreshJobs();if(view==="models")refreshModels()}
function bind(){$$('.nav-item').forEach(button=>button.addEventListener("click",()=>switchView(button.dataset.view)));$("#sourcePicker").addEventListener("click",()=>pickFolder("#sourcePath"));$("#outputPicker").addEventListener("click",()=>pickFolder("#outputPath"));$("#sourcePath").addEventListener("change",()=>{if(!$("#outputPath").value)deriveOutput();updateStartState()});$("#outputPath").addEventListener("input",updateStartState);$("#refreshModels").addEventListener("click",refreshModels);$("#bootstrapModels").addEventListener("click",bootstrapModels);$("#bootstrapModelsLarge").addEventListener("click",bootstrapModels);$("#startButton").addEventListener("click",startJob);$("#refreshJobs").addEventListener("click",refreshJobs);["#targetLanguage","#storyContext","#preserveSfx","#deviceSetting","#preferModelscope"].forEach(id=>$(id).addEventListener("change",saveSettings));$("#contextMinus").addEventListener("click",()=>{$("#contextPages").value=Math.max(0,Number($("#contextPages").value)-1);saveSettings()});$("#contextPlus").addEventListener("click",()=>{$("#contextPages").value=Math.min(12,Number($("#contextPages").value)+1);saveSettings()});$$('[data-preview]').forEach(button=>button.addEventListener("click",()=>{$$('[data-preview]').forEach(item=>item.classList.remove("selected"));button.classList.add("selected");state.previewMode=button.dataset.preview;renderPreview()}));$("#prevPage").addEventListener("click",()=>{state.currentPage=Math.max(1,state.currentPage-1);renderPreview()});$("#nextPage").addEventListener("click",()=>{state.currentPage=Math.min(state.currentJob.total,state.currentPage+1);renderPreview()});const dialog=$("#quickStart");$("#exampleButton").addEventListener("click",()=>dialog.showModal());dialog.querySelector(".dialog-close").addEventListener("click",()=>dialog.close())}
async function init(){bind();try{const[system,settings,modelData]=await Promise.all([api("/api/system"),api("/api/settings"),api("/api/models")]);$("#versionLabel").textContent=`v${system.version} · MIT License`;$("#appHome").textContent=`应用数据目录：${system.home}`;loadSettings(settings);state.models=modelData.models;renderModels();await refreshJobs()}catch(error){toast(error.message,true)}}
init();
