const state={models:[],settings:null,currentJob:null,currentPage:1,previewMode:"compare",pollTimer:null,modelTask:null,activeBackend:null};
const $=(selector)=>document.querySelector(selector);const $$=(selector)=>[...document.querySelectorAll(selector)];
async function api(path,options={}){const response=await fetch(path,{headers:{"Content-Type":"application/json",...(options.headers||{})},...options});if(!response.ok){let message=`HTTP ${response.status}`;try{const body=await response.json();message=body.detail||message}catch{}throw new Error(message)}return response.json()}
function toast(message,error=false){const el=$("#toast");el.textContent=message;el.className=`toast show${error?" error":""}`;clearTimeout(el._timer);el._timer=setTimeout(()=>el.className="toast",3600)}
function escapeHtml(value){return String(value).replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[char])}
function modelIcon(id){return id==="paddleocr"?"PD":id==="manga-ocr"?"漫":id==="lama"?"补":"译"}
function renderModels(){const rows=state.models.map(model=>`<div class="model-row"><span class="model-icon">${modelIcon(model.id)}</span><div><b>${escapeHtml(model.name)}</b><small>${escapeHtml(model.role)} · ${escapeHtml(model.provider)}${model.required?"":" · 当前后端不需要"}</small></div><span class="status-chip ${model.ready?"ready":""}">${model.ready?"已就绪":model.required?"未下载":"可选"}</span></div>`).join("");$("#modelRows").innerHTML=rows||'<div class="empty-list">模型状态不可用</div>';$("#modelListLarge").innerHTML=state.models.map(model=>`<article class="panel utility-item"><div><b>${escapeHtml(model.name)}</b><small>${escapeHtml(model.repository)} · ${escapeHtml(model.size)} · ${escapeHtml(model.license)}</small><small>${escapeHtml(model.path)}</small></div><span class="status-chip ${model.ready?"ready":""}">${model.ready?"已就绪":model.required?"未下载":"当前可选"}</span></article>`).join("");const missing=state.models.filter(model=>model.required&&!model.ready);$("#bootstrapModels").hidden=missing.length===0;$("#bootstrapModelsLarge").textContent=missing.length?`准备 ${missing.length} 个缺失模型`:"所需模型已就绪";$("#bootstrapModelsLarge").disabled=missing.length===0;updateStartState()}
async function refreshModels(){try{const data=await api("/api/models?refresh=true");state.models=data.models;renderModels()}catch(error){toast(error.message,true)}}
async function bootstrapModels(){const missing=state.models.filter(model=>model.required&&!model.ready).map(model=>model.id);if(!missing.length)return;try{const task=await api("/api/models/bootstrap",{method:"POST",body:JSON.stringify({model_ids:missing})});state.modelTask=task.id;$("#modelProgress").hidden=false;pollModelTask()}catch(error){toast(error.message,true)}}
async function pollModelTask(){if(!state.modelTask)return;try{const task=await api(`/api/tasks/${state.modelTask}`);const progress=$("#modelProgress");progress.hidden=false;progress.querySelector("i").style.width=`${task.progress}%`;progress.querySelector("small").textContent=task.message;if(task.status==="complete"){state.modelTask=null;progress.hidden=true;toast("模型已准备完成");await refreshModels()}else if(task.status==="failed"){state.modelTask=null;progress.querySelector("small").textContent=task.error||task.message;toast(task.error||task.message,true)}else setTimeout(pollModelTask,1000)}catch(error){toast(error.message,true)}}
function updateBackendUI(){const backend=$("#inferenceBackend").value;const ocr=$("#ocrBackend").value;$("#inferenceBackendSetting").value=backend;$("#ocrBackendSetting").value=ocr;$("#builtinFields").hidden=backend!=="builtin";$("#ollamaFields").hidden=backend!=="ollama"&&ocr!=="ollama";$("#onlineFields").hidden=backend!=="online";if(state.activeBackend!==null&&state.activeBackend!==`${backend}:${ocr}`){$("#inferenceStatus").textContent="尚未测试连接";$("#inferenceStatus").className="inference-status"}state.activeBackend=`${backend}:${ocr}`;const online=backend==="online";$("#privacyBadgeTitle").textContent=online?"在线翻译模式":"本地推理模式";$("#privacyBadgeDetail").textContent=online?"仅发送识别后的文字":"图片和文字不离开设备";$("#privacyNotice").textContent=online?"图片与排版留在本机；仅 OCR 文字会发送到所选翻译 API":"所有处理均在本机完成，不上传图片";updateStartState()}
function loadSettings(settings){state.settings=settings;$("#targetLanguage").value=settings.target_language;$("#storyContext").checked=settings.story_context;$("#contextPages").value=settings.context_pages;$("#preserveSfx").checked=settings.preserve_sfx;$("#qualityProfile").value=settings.quality_profile||"quality";$("#outputFormat").value=settings.output_format||"webp";$("#deviceSetting").value=settings.device;$("#preferModelscope").checked=settings.prefer_modelscope;$("#ocrBackend").value=settings.ocr_backend||"builtin";$("#ocrBackendSetting").value=settings.ocr_backend||"builtin";$("#inferenceBackend").value=settings.inference_backend;$("#inferenceBackendSetting").value=settings.inference_backend;$("#ollamaBaseUrl").value=settings.ollama_base_url;$("#ollamaModel").value=settings.ollama_model;$("#ollamaOcrModel").value=settings.ollama_ocr_model||"qwen2.5vl:7b";$("#onlineBaseUrl").value=settings.online_base_url;$("#onlineModel").value=settings.online_model;$("#onlineApiKey").value="";$("#onlineApiKey").placeholder=settings.online_api_key_configured?"当前会话已配置；留空保持不变":"可使用 MLS_ONLINE_API_KEY";updateBackendUI()}
function collectSettings(){const settings={target_language:$("#targetLanguage").value,story_context:$("#storyContext").checked,context_pages:Number($("#contextPages").value),preserve_sfx:$("#preserveSfx").checked,quality_profile:$("#qualityProfile").value,output_format:$("#outputFormat").value,prefer_modelscope:$("#preferModelscope").checked,device:$("#deviceSetting").value,ocr_backend:$("#ocrBackend").value,inference_backend:$("#inferenceBackend").value,ollama_base_url:$("#ollamaBaseUrl").value.trim(),ollama_model:$("#ollamaModel").value.trim(),ollama_ocr_model:$("#ollamaOcrModel").value.trim(),online_base_url:$("#onlineBaseUrl").value.trim(),online_model:$("#onlineModel").value.trim()};const key=$("#onlineApiKey").value.trim();if(key)settings.online_api_key=key;return settings}
async function saveSettings(){const settings=collectSettings();try{loadSettings(await api("/api/settings",{method:"PUT",body:JSON.stringify(settings)}));await refreshModels()}catch(error){toast(error.message,true)}}
async function checkInference(){const status=$("#inferenceStatus");status.className="inference-status";status.textContent="正在测试连接…";try{const result=await api("/api/inference/check",{method:"POST",body:JSON.stringify(collectSettings())});status.textContent=result.message;status.className=`inference-status ${result.ok?"ready":"error"}`;$("#inferenceModels").innerHTML=result.models.map(model=>`<option value="${escapeHtml(model)}"></option>`).join("")}catch(error){status.textContent=error.message;status.className="inference-status error"}}
async function pickFolder(target){try{const initial=$(target).value||null;const result=await api("/api/dialog/folder",{method:"POST",body:JSON.stringify({initial})});if(result.path){$(target).value=result.path;if(target==="#sourcePath"&&!$("#outputPath").value)await deriveOutput();updateStartState()}}catch(error){toast(`${error.message}；也可以直接输入绝对路径。`,true)}}
async function deriveOutput(){const source=$("#sourcePath").value.trim();if(!source)return;try{const result=await api("/api/paths/derive-output",{method:"POST",body:JSON.stringify({initial:source})});$("#outputPath").value=result.path;updateStartState()}catch(error){toast(error.message,true)}}
function updateStartState(){const reviewed=!!$("#reviewedTranscript")?.value.trim();const missing=!reviewed&&state.models.some(model=>model.required&&!model.ready);const running=state.currentJob&&["queued","running"].includes(state.currentJob.status);const backend=$("#inferenceBackend")?.value||"builtin";const ocr=$("#ocrBackend")?.value||"builtin";const missingName=!reviewed&&((backend==="ollama"&&!$("#ollamaModel")?.value.trim())||(backend==="online"&&!$("#onlineModel")?.value.trim())||(ocr==="ollama"&&!$("#ollamaOcrModel")?.value.trim()));$("#startButton").disabled=!$("#sourcePath").value.trim()||!$("#outputPath").value.trim()||missing||missingName||running;$("#startButton").title=missing?"请先准备缺失模型":missingName?"请填写推理模型名称":""}
async function startJob(){const payload={source:$("#sourcePath").value.trim(),output:$("#outputPath").value.trim(),...collectSettings(),glossary:{},reviewed_transcript:$("#reviewedTranscript").value.trim()||null};try{state.currentJob=await api("/api/jobs",{method:"POST",body:JSON.stringify(payload)});state.currentPage=1;renderJob(state.currentJob);pollJob()}catch(error){toast(error.message,true)}}
function phaseIndex(job){if(job?.phase==="ocr")return job.total&&job.current/job.total>=.5?1:0;if(job?.phase==="translate")return 2;if(job?.phase==="render"||job?.phase==="complete")return 3;return 0}
function renderPipeline(job){const active=phaseIndex(job);$$('.pipeline-step').forEach((step,index)=>{step.classList.toggle("done",job?.status==="complete"||index<active);step.classList.toggle("active",job?.status==="running"&&index===active)});$$('.step-line').forEach((line,index)=>line.classList.toggle("done",job?.status==="complete"||index<active));$("#pipelineEstimate").textContent=job?.status==="running"?`${job.progress}%`:job?.status==="complete"?"已完成":"等待开始"}
function renderJob(job){state.currentJob=job;renderPipeline(job);$("#jobMessage").textContent=job.message||"等待开始";$("#jobDetail").textContent=job.error||`${job.phase||"queued"} · 本地任务`;$("#jobProgress").style.width=`${job.progress||0}%`;$("#jobCount").textContent=`${job.current||0} / ${job.total||0}`;$("#pageTotal").textContent=job.total||0;$("#pageNumber").textContent=job.total?state.currentPage:0;$("#activityRing").style.animation=job.status==="running"?"spin 1s linear infinite":"none";updateStartState();if(job.total)renderPreview();if(job.status==="failed")toast(job.error||"任务失败",true)}
async function pollJob(){clearTimeout(state.pollTimer);if(!state.currentJob)return;try{const job=await api(`/api/jobs/${state.currentJob.id}`);renderJob(job);if(["queued","running"].includes(job.status))state.pollTimer=setTimeout(pollJob,1000);else if(job.status==="complete"){toast("本地化完成");await refreshJobs()}}catch(error){toast(error.message,true)}}
function setPreviewImage(image,url,key){if(image.dataset.previewKey===key)return;image.dataset.previewKey=key;image.hidden=false;image.src=`${url}?t=${Date.now()}`}
function outputPreviewReady(job,page){return job.status==="complete"||job.phase==="complete"||(job.phase==="render"&&Number(job.current)>=page)}
function pendingPreviewMessage(job){if(job.phase==="ocr")return "等待 OCR 完成";if(job.phase==="translate")return "等待连贯翻译完成";if(job.status==="failed")return "任务失败，暂无译文页面";return "等待生成译文页面"}
function renderPreview(){const job=state.currentJob;if(!job||!job.total)return;const canvas=$("#previewCanvas");canvas.className=`preview-canvas mode-${state.previewMode}`;canvas.classList.remove("empty");const source=$("#sourcePreview");const output=$("#outputPreview");const pending=$("#outputPending");const sourceKey=`${job.id}:source:${state.currentPage}`;setPreviewImage(source,`/api/jobs/${job.id}/preview/source/${state.currentPage}`,sourceKey);if(outputPreviewReady(job,state.currentPage)){pending.hidden=true;const outputKey=`${job.id}:output:${state.currentPage}`;setPreviewImage(output,`/api/jobs/${job.id}/preview/output/${state.currentPage}`,outputKey);output.onerror=()=>{output.hidden=true;pending.hidden=false;pending.textContent="译文页面暂不可用";output.removeAttribute("src");delete output.dataset.previewKey}}else{output.hidden=true;output.removeAttribute("src");delete output.dataset.previewKey;pending.hidden=false;pending.textContent=pendingPreviewMessage(job)}$("#previewName").textContent=`第 ${state.currentPage} 页`;$("#pageNumber").textContent=state.currentPage;$("#prevPage").disabled=state.currentPage<=1;$("#nextPage").disabled=state.currentPage>=job.total}
async function refreshJobs(){try{const data=await api("/api/jobs");const list=$("#jobList");list.innerHTML=data.jobs.length?data.jobs.map(job=>`<button class="panel utility-item job-item" data-job-id="${job.id}"><div><b>${escapeHtml(job.request.source)}</b><small>${escapeHtml(job.message)} · ${job.progress}% · ${escapeHtml(job.updated_at)}</small></div><span class="status-chip ${job.status==="complete"?"ready":job.status==="failed"?"error":""}">${escapeHtml(job.status)}</span></button>`).join(""):'<div class="panel empty-list">还没有任务记录</div>';$$('.job-item').forEach(button=>button.addEventListener("click",async()=>{const job=await api(`/api/jobs/${button.dataset.jobId}`);renderJob(job);switchView("workspace")}))}catch(error){toast(error.message,true)}}
function switchView(view){$$('.nav-item').forEach(button=>button.classList.toggle("active",button.dataset.view===view));$$('.view').forEach(panel=>panel.classList.toggle("active",panel.dataset.viewPanel===view));const labels={workspace:"漫画本地化工作台",history:"任务记录",models:"模型管理",settings:"设置"};$("#pageTitle").textContent=labels[view]||labels.workspace;if(view==="history")refreshJobs();if(view==="models")refreshModels()}
function bind(){$$('.nav-item').forEach(button=>button.addEventListener("click",()=>switchView(button.dataset.view)));$("#sourcePicker").addEventListener("click",()=>pickFolder("#sourcePath"));$("#outputPicker").addEventListener("click",()=>pickFolder("#outputPath"));$("#sourcePath").addEventListener("change",()=>{if(!$("#outputPath").value)deriveOutput();updateStartState()});$("#outputPath").addEventListener("input",updateStartState);$("#refreshModels").addEventListener("click",refreshModels);$("#bootstrapModels").addEventListener("click",bootstrapModels);$("#bootstrapModelsLarge").addEventListener("click",bootstrapModels);$("#startButton").addEventListener("click",startJob);$("#refreshJobs").addEventListener("click",refreshJobs);$("#checkInference").addEventListener("click",checkInference);["#targetLanguage","#storyContext","#preserveSfx","#qualityProfile","#outputFormat","#deviceSetting","#preferModelscope","#ollamaBaseUrl","#ollamaModel","#ollamaOcrModel","#onlineBaseUrl","#onlineModel","#onlineApiKey"].forEach(id=>$(id).addEventListener("change",saveSettings));[["#inferenceBackend","#inferenceBackendSetting"],["#ocrBackend","#ocrBackendSetting"]].forEach(pair=>pair.forEach(id=>$(id).addEventListener("change",event=>{const target=id.includes("ocrBackend")?"#ocrBackend":"#inferenceBackend";$(target).value=event.target.value;updateBackendUI();saveSettings()})));$("#contextMinus").addEventListener("click",()=>{$("#contextPages").value=Math.max(0,Number($("#contextPages").value)-1);saveSettings()});$("#contextPlus").addEventListener("click",()=>{$("#contextPages").value=Math.min(12,Number($("#contextPages").value)+1);saveSettings()});$$('[data-preview]').forEach(button=>button.addEventListener("click",()=>{$$('[data-preview]').forEach(item=>item.classList.remove("selected"));button.classList.add("selected");state.previewMode=button.dataset.preview;renderPreview()}));$("#prevPage").addEventListener("click",()=>{state.currentPage=Math.max(1,state.currentPage-1);renderPreview()});$("#nextPage").addEventListener("click",()=>{state.currentPage=Math.min(state.currentJob.total,state.currentPage+1);renderPreview()});const dialog=$("#quickStart");$("#exampleButton").addEventListener("click",()=>dialog.showModal());dialog.querySelector(".dialog-close").addEventListener("click",()=>dialog.close())}
async function init(){bind();try{const[system,settings,modelData]=await Promise.all([api("/api/system"),api("/api/settings"),api("/api/models")]);$("#versionLabel").textContent=`v${system.version} · MIT License`;$("#appHome").textContent=`应用数据目录：${system.home}`;loadSettings(settings);state.models=modelData.models;renderModels();await refreshJobs()}catch(error){toast(error.message,true)}}
init();
